//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomanaDe10.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RomanaDe10.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexandru Lăpușneanul
        ///Costache Negruzzi
        ///~nuvelă istorică~
        ///
        ///	Considerată prima nuvelă istorică românească, opera lui Costache Negruzzi Alexandru Lăpuşneanul apare în anul 1840, în revista „Dacia literară”, încadrându-se perfect în programul romantic al acesteia, prin valorificarea unor fapte istorice şi prin crearea de tipuri vii, puternice, sfâşiate lăuntric de manifestări adesea contradictorii.
        ///	Ea respectă toate exigenţele speciei literare pe care o reprezintă – nuvela. Structura este riguroasă, conf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Alexandru_Lăpușneanul {
            get {
                return ResourceManager.GetString("Alexandru_Lăpușneanul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltagul
        ///Mihail Sadoveanu
        ///~roman tradițional~
        ///
        ///Opera sadoveniană Baltagul descrie o lume arhaică, păstrătoare a tradiţiilor şi a obiceiurilor, impresionantă prin frumuseţea morală a eroinei, pornite în căutarea soţului dispărut, în căutarea adevărului. Venind din folclor, din Neculce şi Creangă, Sadoveanu este un scriitor de tip rapsodic, un evocator, un temperament liric, un povestitor care îşi proiectează în mit, în legendă, propria viziune, personajele, aventurile lor epice, spaţiul şi timpul. Totul  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Baltagul {
            get {
                return ResourceManager.GetString("Baltagul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap design {
            get {
                object obj = ResourceManager.GetObject("design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enigma Otiliei
        ///G. Călinescu
        ///~ roman realist, de factură balzaciană~
        ///
        ///	Roman realist, de inspiraţie citadină, opera literară Enigma Otiliei fixează, în spirit balzacian, aspecte ale vieţii burgheziei bucureştene de la începutul secolului XX, zugrăvită în datele ei esenţiale. Tema socială este adâncită prin fixarea unor tipologii, cercetate analitic, iar întreaga reconstituire de împrejurări, destine şi tipuri umane poartă pecetea „ credibilităţii.” 
        ///	Pentru că „nu există fenomen artistic pur, clasic sau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Enigma_Otiliei {
            get {
                return ResourceManager.GetString("Enigma_Otiliei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eseu {
            get {
                object obj = ResourceManager.GetObject("eseu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eu nu strivesc corola de minuni a lumii
        ///Lucian Blaga
        ///
        ///Citat: ,,Omul trebuie să fie un creator, - de aceea renunț cu bucurie la cunoașterea absolutului.” ( Lucian Blaga, Pietre pentru templul meu)
        ///      Ca și la Mihai Eminescu, în lirica lui Blaga există un plan filozofic secundar, creația sa fiind un spațiu al experietelor esențiale.
        ///      Poet și filozof, Lucian Blaga transpune în lirică cele două concepte filozofice originale: cunoașterea luciferică și cunoașterea paradisiacă. Cunoașterea paradisiacă [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eu_nu_strivesc_corola_de_minuni_a_lumii {
            get {
                return ResourceManager.GetString("Eu_nu_strivesc_corola_de_minuni_a_lumii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floare albastră
        ///Mihai Eminescu
        ///
        ///      Poezia Floare albastră, de Mihai Eminescu, fundamentează motivul poetic al „florii albastre”, întâlnit la romanticii europeni pentru a ilustra sentimentul de dragoste sau chipul iubitei, precum şi tendinţa de proiectare a iubirii în infinit.
        ///Deşi nu s-a găsit nicăieri o însemnare făcută de Eminescu privind preluarea acestui motiv literar, George Călinescu susţine că este imposibil ca poetul român să nu fi avut cunoştinţă de existenţa acestuia în literatura germană,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Floare_albastră {
            get {
                return ResourceManager.GetString("Floare_albastră", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flori de mucigai
        ///Tudor Arghezi
        ///
        ///Citat: Arghezi a înnoit poezia românească. (Eugen Simion)
        ///      Literatura interbelică este dominată de manifestarea a două direcții principale: tradiționalismul şi modernismul. Modernismul cuprinde mișcările artistice care exprimă, în mod categoric, desprinderea de tradiție. Moderniştii sunt atraşi de metafizică şi transcendenţă, făcând din cunoașterea spirituală o preocupare esențială. În poezia românească, modernismul poate fi recunoscut în expresionismul lui Lucian Bl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Flori_de_mucigai {
            get {
                return ResourceManager.GetString("Flori_de_mucigai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to În grădina Ghetsemani
        ///Vasile Voiculescu
        ///
        ///Citat: „Capodopera lui V. Voiculescu-pastelistul ramane, fara discutie, Pe decin-dea Dunarii, text de subtile armonii sonore si perfecta structurare a miscarii si tuselor coloristice, sugerand continuitatea destinului istoric al neamului, contopirea cu stramosii indepartati, in ritmul solemn al timpului.&quot; (Ion Pop)
        ///      Poet autentic religios, Vasile Voiculescu a publicat peste 100 de poezii în revista „Gândirea”, rămânându-i loial o lungă perioadă, din 1927 pân [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string În_grădina_Ghetsemani {
            get {
                return ResourceManager.GetString("În_grădina_Ghetsemani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ION
        ///Liviu Rebreanu
        ///- roman realist-obiectiv; roman interbelic-
        ///
        ///Într-o epocă ce denunţa criza romanului românesc, opera romancierului L. Rebreanu reprezintă prima contribuţie fundamentală la crearea romanului românesc modern.
        ///Romanul apare în perioada interbelică, anul 1920 reprezentând „o dată istorică în procesul obiectivării literaturii noastre epice”.
        ///Epoca interbelică este marcată de două orientări literare: modernismul și tradiționalismul. Deși prin tema literară romanul lui Rebreanu este unul s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ion {
            get {
                return ResourceManager.GetString("Ion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iona
        ///                                                                      Marin Sorescu
        ///~dramă modernă~
        ///Piesa ,,Iona” este publicată în anul 1968, în revista ,,Luceafărul”, făcând parte din triologia ,,Setea muntelui de sare”, alături de „Paracliserul” și „Matca”.
        ///Aparent, piesa are ca punct de plecare mitul biblic al lui Iona. Trimis de către Dumnezeu în cetatea Ninive, loc al desfrâului, pentru a propovădui cuvântul divin, pescarul Iona se simte împovărat de această misiune și fuge pe mare. Dumnezeu  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Iona {
            get {
                return ResourceManager.GetString("Iona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leoaică tânără, iubirea
        ///Nichita Stănescu
        ///Citat: ,,Poezia lui Nichita Stănescu e un imn involuntar, dedicat Maiestății Sale Cuvântul și antinomiilor lui Necuvântul” (Constantin Crișan)
        ///      Poetul ,,se face că se joacă cu niște jucării ce se cheamă univers, destin, existență, iubire, moarte, singurătate” (Eugen Simion)
        ///      Prezentându-și concepția literară, într-un eseu din tinerețe, Nichita Stănescu scria: ,,clasicul vede idei, romanticul sentimente, modernul vede deodată și ideile și sentimentele, d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Leoaică_tânără__iubirea {
            get {
                return ResourceManager.GetString("Leoaică_tânără__iubirea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moara cu noroc
        ///Ioan Slavici
        ///~nuvelă realist-psihologică~
        ///
        ///	Istoria literară îl situează pe Slavici în Epoca marilor clasici, alături de Mihai Eminescu, Ion Creangă și I.L.Caragiale.
        /// 	Scriitor de factură realistă, precursor al lui Rebreanu, prozatorul oferă o imagine verosimilă asupra satului transilvănean din primele decenii ale secolului al XIX-lea; se remarcă prin acuitatea observației sociale, prin personajele complexe create, prin profunzimea analizei psihologice, dar mai ales prin substratul mora [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Moara_cu_noroc {
            get {
                return ResourceManager.GetString("Moara_cu_noroc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moromeţii
        ///							Marin Preda
        ///~roman postbelic, realist~
        ///
        ///Scriitor realist modern, M.Preda este creatorul unui roman tulburator prin sensurile lui, prin universul artistic si personajul creat 
        ///Ca orice roman, el reprezintăo scriere amplă in proză, acţiunea desfăşurându-se pe mai multe planuri narative, care ajung să interfereze sau chiar să se suprapună, din nevoia de a surprinde viaţa în complexitatea ei, element definitoriu (esenţial) în orice paradigmă a romanescului. Personajele, cu o pondere diferi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Moromeții {
            get {
                return ResourceManager.GetString("Moromeții", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O scrisoare pierdută
        ///I.L.Caragiale
        ///~gen dramatic, comedie~
        ///
        ///	Considerat până astăzi cel mai mare dramaturg al literaturii române, I.L.Caragiale aparține Epocii Marilor Clasici, alături de Ion Creangă, Ioan Slavici și Mihai Eminescu. Prin comediile sale – „O scrisoare pierdută”, „O noapte furtunoasă”, „Conu&apos; Leonida față cu reacțiunea” și „D-ale carnavalului”- se prezintă moravurile vieții politice și de familie ale burgheziei secolului al XIX-lea.
        ///	Deși opera lui Caragiale se înscrie în estetica litera [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string O_scrisoare_pierdută {
            get {
                return ResourceManager.GetString("O_scrisoare_pierdută", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pana {
            get {
                object obj = ResourceManager.GetObject("pana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumb
        ///George Bacovia
        ///
        ///Citat: Fiecărui sentiment îi corespunde o culoare. Acum în urmă m¬-a obsedat galbenul, culoarea deznădejdei…În plumb văd culoarea galbenă. […] Plumbul ars e galben. Sufletul ars e galben. […] Altădată, în Plumb, pe lângă impresia colorată, mai simțeam alta static, de greutate. Plumbul apasă cel mai greu pe om… Cât privește despre mine am fost și rămân un poet al decadenței . ( Interviu al poetului în revista Viața literară)
        ///      Opera “Plumb” de George Bacovia deschide volumul de  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Plumb {
            get {
                return ResourceManager.GetString("Plumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povestea lui Harap-Alb
        ///Ion Creangă
        ///~basm cult~
        ///
        ///Opera lui Ion Creangă s-a statornicit în literatură ca unul dintre cele mai rezistente momente ale prozei artistice româneşti durabile, tocmai pentru că a reuşit să prindă în ea sensul vieţii, substanţa sufletului românesc, vigoarea realistă. Opera sa devine „o simbioză organică a optimismului şi umanismului structural al poporului, o îmbinare între valoarea limbii şi ficţiunea populară.”
        ///Opera lui Ion Creangă, Povestea lui Harap-Alb prezintă particularit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Povestea_lui_Harap_Alb {
            get {
                return ResourceManager.GetString("Povestea_lui_Harap_Alb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap progres {
            get {
                object obj = ResourceManager.GetObject("progres", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quiz {
            get {
                object obj = ResourceManager.GetObject("quiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riga Crypto și lapona Enigel
        ///Ion Barbu
        ///Citat: ,,Ca în geometrie înțeleg prin poezie o anumită simbolistică pentru reprezentarea formelor posibile de existență, întrucât există undeva, în domeniul înalt al geometriei, un loc luminous, unde se întâlnește cu poezia.” (Ion Barbu)
        ///      Alături de Tudor Arghezi și Lucian Blaga, Ion Barbu dă conceptului modern de poezie noi valori, impunznd o viziune poetică originală.
        ///      Matematicianul Dan Barbilian devine poet din ambitia de a-i demonstra colegului și pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Riga_Crypto_și_lapona_Enigel {
            get {
                return ResourceManager.GetString("Riga_Crypto_și_lapona_Enigel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap signin {
            get {
                object obj = ResourceManager.GetObject("signin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tabla {
            get {
                object obj = ResourceManager.GetObject("tabla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima noapte de dragoste, întâia noapte de război
        ///Camil Petrescu
        ///~roman modern, subiectiv-analitic~
        ///
        ///Scriitor interbelic, modern, Camil Petrescu adoptă formula romanului subiectiv, de analiză psihologică și respinge ideea romanului obiectiv-realist, considerând că se impune „o nouă structură” narativă sincronizată (armonizată) cu psihologia vremii.
        ///	Conceptul fundamental care stă la baza noului roman este cel de autenticitate. În viziunea prozatorului, autentică este experiența trăită în mod direct, t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ultima_noapte_de_dragoste__întâia_noapte_de_război {
            get {
                return ResourceManager.GetString("Ultima_noapte_de_dragoste__întâia_noapte_de_război", resourceCulture);
            }
        }
    }
}
